### PR TITLE
Kubernetes docs

### PR DESCRIPTION
**Pull request by mschneider82**
This PR is for the Documentation

### CODE REVIEW

**Comment by acouvreur** [comment]
How does Traefik reacts when a router has no replicas ? Does it still redirects to the service, or does it evicts the deployment from its routing ?

I never used Traefik with k8s at this time.

**Comment by mschneider82** [comment]
thats why its important to set  - "--providers.kubernetesingress.allowEmptyServices=true"  otherwhise it will does not forward to the waiting page.

It works pretty fine

**Comment by acouvreur** [comment]
> thats why its important to set - "--providers.kubernetesingress.allowEmptyServices=true" otherwhise it will does not forward to the waiting page.
> 
> It works pretty fine

Well that's neat, I wonder why there is no option for swarm except `- traefik.docker.lbswarm=true` which does it behind the scenes.

**Comment by acouvreur** [comment]
I think we could move this documentation to the https://github.com/acouvreur/traefik-ondemand-plugin repository though. Or at least the "tutorial" part. What do you think ?

**Comment by mschneider82** [comment]
I would link it from plugin to here - because its mostly about installing and configuration this service. The plugin stays the same

**Pull request merged**
